<?php
/**
 * @var \ChatGpt\InputValue\Block\Chat $block
 */
?>
<div class="container-greeting">
    <h2><?= $block->getGreeting()?></h2>
</div>
<div class="container-input-value" id="input-value" data-bind="scope:'ko_input'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ko_input": {
                        "component": "ChatGpt_InputValue/js/input_value"
                    }
                }
            }
        }
    }
</script>